# Generated by Django 2.2.28 on 2022-06-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('plans', '0002_seeding'),
    ]

    operations = [
    ]
