# Generated by Django 2.2.28 on 2022-06-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20220620_0847'),
    ]

    operations = [
    ]
