# Generated by Django 2.2.28 on 2022-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(choices=[('Web', 'Web Application'), ('Mobile', 'Mobile Application')])),
                ('framework', models.TextField(blank=True, choices=[('Django', 'Django Framework'), ('React Native', 'React Native Framework')], null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
                ('screenshot', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
